NUMPY

# NUMPY IS MEMORY EFFICIENT

In [9]:
import numpy as np
import sys
s = 100000


l1 = list(range(s))    #python-list
a1 = np.arange(s)      #numpy-array


print("size of memory taken by the python list =",sys.getsizeof(5)*s)  #size of memory taken by the python list
print("size of memory taken by numpy array = ",a1.itemsize*s)          #size of memory taken by numpy array

size of memory taken by the python list = 2800000
size of memory taken by numpy array =  400000


# NUMPY IS TIME-EFFICIENT

In [20]:


import time
s = 10000000
l1 = list(range(s))   #python-list in '0-s' range
l2 = list(range(s,2*s)) #python-list in 's-2s' range
a1 = np.arange(s)     #Numpy-array in '0-s' range
a2 = np.arange(s,2*s)   #Numpy-array in '0-s' range


st = time.time()   #start time

l3 = [(x+y)for x,y in zip(l1,l2)] #adding coressponding elements and making new list 

end = time.time() #end time
print(end-st) #total - time taken to add python-list

st = time.time()   #start time

a3 = a1+a2

end = time.time() #end time
print(end-st) #total - time taken to add numpy array
# print(a3)

3.1067819595336914
0.09001970291137695


# ZEROS - METHOD

this method create an array with zero values
(Numpy is nothing but an array)

In [24]:
a = np.zeros(10)
print(a)  #By default print float values


a = np.zeros(10 , dtype = np.int) #to get specific datatype we use 'dtype'
print(a)  

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]


# Ones - method

all values in array will be one

In [25]:
a = np.ones(10)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


# Creating a 2-d array

In [26]:
#np.method((row,column))
#for multi-dimensional array we use double tupples (())

a = np.zeros((3,4))  
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [29]:
# 2-d Array of random number

a = np.random.random((3,3))
print(a)

[[0.52369381 0.59451536 0.99322701]
 [0.34244283 0.61306265 0.55978105]
 [0.5630232  0.35884428 0.82844411]]


In [31]:
# creating an 1-d array using arange method

a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [40]:
# creating an 2-d array using arange method and reshape method

a = np.arange(12).reshape(2,6)  #always remember to give multiple of the range to get it reshaped i.e 2*6=12
a
# print(a.dtype)
# print(a.ndim)
# print(a.shape)
# print(a.size)

int32
2
(2, 6)
12


In [55]:
a1 = np.arange(0,4).reshape(2,2)
a2 = np.arange(4,8).reshape(2,2)
print("A1=",a1)
print("A2=",a2)
# print("add=",a1+a2)
# print("sub",a1-a2)
# print("div",a1/a2)
# print("mul",a1*a2)
# print("MATRIX-MULTIPLICATION",a1.dot(a2))

A1= [[0 1]
 [2 3]]
A2= [[4 5]
 [6 7]]


In [54]:
#VERTICAL AND HORIZONTAL STACK

print(np.vstack((a1,a2)))
print(np.hstack((a1,a2)))

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0 1 4 5]
 [2 3 6 7]]


In [56]:
# Square-root
print(np.sqrt(a1))

[[0.         1.        ]
 [1.41421356 1.73205081]]


In [58]:
# Linspace
a = np.linspace(0,5,10)  #linspace(start-range,end-range,in-between elements)
print(a)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [64]:
#SOME PREDIFINED FUNCTIONS
print(a.sum())
print(a.max())
print(a.min())
print(a.mean())
print(a.std())


25.0
5.0
0.0
2.5
1.5957118462605635


In [69]:

a = np.arange(9).reshape(3,3)
print(a)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [77]:
print(a.sum(axis=0))  #sum between columns

[ 9 12 15]


In [79]:
print(a.sum(axis=1)) #sum between rows

[ 3 12 21]


In [80]:
a = np.arange(12)
print(a[0]) #first-element

0


In [81]:
print(a[-1]) #last-element

11


In [82]:
print(a[0:2])  #first-two element

[0 1]


In [83]:
print(a[2:]) #starting from 2

[ 2  3  4  5  6  7  8  9 10 11]


In [84]:
print(a[-2:]) #starting from last 2nd

[10 11]


In [85]:
print(a[::2]) #print in interval of 2

[ 0  2  4  6  8 10]


In [86]:
print(a[::-1]) #reverse order

[11 10  9  8  7  6  5  4  3  2  1  0]


In [87]:
print(a[:]) #all print

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [91]:
#Handling a numpy arange()

a = np.arange(12).reshape(3,4)
print(a)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [92]:
# print(a[Row,Column])

print(a[0,2:]) #last two elemnts of first row

[2 3]


In [94]:
print(a[0:3,0])  #fisrt 3 elements of first columns

[0 4 8]


In [95]:
print(a[:2,:2])

[[0 1]
 [4 5]]


In [96]:
print(a[:2,::2])

[[0 2]
 [4 6]]


In [97]:
print(a[:2,(0,3)])

[[0 3]
 [4 7]]
